test-llm:
  api_key: '<private-key>'
  api_version: "<api-version>"
  endpoint: "<endpoint>"
  model: "<model-name>"
  deployment_name: '<deployment-name>'
  temperature: 0.7
  streaming: true

llm:
  api_key: '<private-key>'
  api_version: "<api-version>"
  endpoint: "<endpoint>"
  model: "<model-name>"
  deployment_name: '<deployment-name>'
  temperature: 0.7
  streaming: true

embeddings:
  api_key: '<private-key>'
  api_version: "<api-version>"
  endpoint: "<endpoint>"
  model: "<model-name>"
  deployment_name: '<deployment-name>'

chromadb:
  host: "<endpoint>"
  port: 8000
  ssl: False
  #persist_directory: './chroma/chroma'
  
langsmith:
  langchain_tracing_v2: 'true'
  langchain_endpoint: "https://api.smith.langchain.com"
  langchain_api_key: "<your-api-key>"
  langchain_project: "my-project"